// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResgistroJugadores.Context;

#nullable disable

namespace ResgistroJugadores.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20250920211353_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("ResgistroJugadores.Models.Jugadores", b =>
                {
                    b.Property<int>("JugadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Derrotas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Empates")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Victorias")
                        .HasColumnType("INTEGER");

                    b.HasKey("JugadorId");

                    b.ToTable("Jugadores");
                });

            modelBuilder.Entity("ResgistroJugadores.Models.Movimientos", b =>
                {
                    b.Property<int>("MovimientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("TEXT");

                    b.Property<int>("JugadorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartidaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PosicionColumna")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PosicionFila")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovimientoId");

                    b.HasIndex("JugadorId");

                    b.HasIndex("PartidaId");

                    b.ToTable("Movimientos");
                });

            modelBuilder.Entity("ResgistroJugadores.Models.Partida", b =>
                {
                    b.Property<int>("PartidaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EstadoPartida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("EstadoTablero")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GanadorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Jugador1Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Jugador2Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TurnoJugadorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PartidaId");

                    b.HasIndex("GanadorId");

                    b.HasIndex("Jugador1Id");

                    b.HasIndex("Jugador2Id");

                    b.HasIndex("TurnoJugadorId");

                    b.ToTable("Partidas");
                });

            modelBuilder.Entity("ResgistroJugadores.Models.Movimientos", b =>
                {
                    b.HasOne("ResgistroJugadores.Models.Jugadores", "Jugadores")
                        .WithMany("Movimientos")
                        .HasForeignKey("JugadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResgistroJugadores.Models.Partida", "Partidas")
                        .WithMany()
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jugadores");

                    b.Navigation("Partidas");
                });

            modelBuilder.Entity("ResgistroJugadores.Models.Partida", b =>
                {
                    b.HasOne("ResgistroJugadores.Models.Jugadores", "Ganador")
                        .WithMany()
                        .HasForeignKey("GanadorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ResgistroJugadores.Models.Jugadores", "Jugador1")
                        .WithMany()
                        .HasForeignKey("Jugador1Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ResgistroJugadores.Models.Jugadores", "Jugador2")
                        .WithMany()
                        .HasForeignKey("Jugador2Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ResgistroJugadores.Models.Jugadores", "TurnoJugador")
                        .WithMany()
                        .HasForeignKey("TurnoJugadorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Ganador");

                    b.Navigation("Jugador1");

                    b.Navigation("Jugador2");

                    b.Navigation("TurnoJugador");
                });

            modelBuilder.Entity("ResgistroJugadores.Models.Jugadores", b =>
                {
                    b.Navigation("Movimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
